global:
  message: Welcome to customer service dev env!
server:
  port: 8082
message: this is hello from Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password: 
  jpa: 
    hibernaate:
      ddl-auto: update
    show-sql: true
