global:
  message: Welcome to customer service production env!
server:
  port: 8083
message: this is hello from Prod!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_prod
    username: root
    password: 
  jpa: 
    hibernaate:
      ddl-auto: update
    show-sql: true
