global:
  message: Welcome to order service production env!
server:
  port: 8085
message: this is hello from order Prod!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: 
  jpa: 
    hibernaate:
      ddl-auto: update
    show-sql: true
